CREATE TABLE IF NOT EXISTS filme (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    titulo TEXT NOT NULL,
    data_lancamento DATE NOT NULL,
    ano INTEGER NOT NULL,
    duracao INTEGER NOT NULL,
    genero TEXT NOT NULL,
    diretor TEXT NOT NULL,
    atores TEXT NOT NULL,
    sinopse TEXT NOT NULL,
    classificacao TINYINT NOT NULL,
    em_cartaz BIT DEFAULT 0,
    idioma TEXT,
    pais TEXT,
    imdb TINYINT,
    poster TEXT,
    banner TEXT,
    trailer_url TEXT
);

CREATE TABLE IF NOT EXISTS sala (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    quantidade_fileira TINYINT NOT NULL,
    quantidade_assento TINYINT NOT NULL,
    tipo_sala TEXT DEFAULT 'Normal'
);

CREATE TABLE IF NOT EXISTS usuario (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    data_nascimento DATE NOT NULL,
    senha TEXT NOT NULL,
    email TEXT NOT NULL,
    cpf TEXT NOT NULL UNIQUE,
    endereco TEXT,
    admin BIT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS telefone (
    telefone TEXT NOT NULL,
    usuario_id INTEGER NOT NULL,
    PRIMARY KEY (telefone, usuario_id)
);

CREATE TABLE IF NOT EXISTS sessao (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sala_id INTEGER NOT NULL,
    filme_id INTEGER NOT NULL,
    data_horario_inicio DATETIME NOT NULL,
    formato TEXT DEFAULT '2D',
    dublado BIT default 0,
    FOREIGN KEY (sala_id) REFERENCES sala(id),
    FOREIGN KEY (filme_id) REFERENCES filme(filme_id)
);

CREATE TABLE IF NOT EXISTS tipo_ingresso (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    preco DECIMAL(7, 2) NOT NULL,
    observacao TEXT
);

CREATE TABLE IF NOT EXISTS ingresso (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tipo_ingresso_id INTEGER NOT NULL,
    sessao_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    poltrona TEXT NOT NULL,
    data_compra DATETIME DEFAULT current_timestamp,
    FOREIGN KEY (tipo_ingresso_id) REFERENCES tipo_ingresso(id),
    FOREIGN KEY (sessao_id) REFERENCES sessao(id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    UNIQUE (sessao_id, poltrona)
);

INSERT INTO tipo_ingresso (id, nome, preco, observacao) VALUES (1, 'Ingresso individual', 10.50, 'Ingresso normal avulso');
INSERT INTO tipo_ingresso (id, nome, preco, observacao) VALUES (2, 'Ingresso familia', 35.99, 'Ingresso para toda a fámilia. Válido para 2 adultos e 2 crianças');
INSERT INTO tipo_ingresso (id, nome, preco, observacao) VALUES (3, 'Ingresso casal', 16.70, 'Ingresso para os amantes. Válido para 2 pessoas');


INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (1, 'Sonic: O Filme', '2020-02-12', 2020, 99, 'Ação;Ficção Científica;Comédia;Familía', 'Jeff Fowler', 'Ben Schwartz;James Marsden;Jim Carrey','Sonic, o ouriço azul mais famoso do mundo, se junta com os seus amigos para derrotar o terrível Doutor Eggman, um cientista louco que planeja dominar o mundo, e o Doutor Robotnik, responsável por aprisionar animais inocentes em robôs.', 0,1,'Inglês','Estados Unidos',6.9,'/Kt9iFdTu5TbAm7tNfc876mrWU.jpg','/qonBhlm0UjuKX2sH7e73pnG0454.jpg','zQEjE_M2Esw');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (2, 'Aves de Rapina: Arlequina e sua Emancipação Fantabulosa', '2020-12-07', 2020, 109, 'Ação;Crime;Comédia', 'Cathy Yan', 'Margot Robbie;Ewan McGregor;Mary Elizabeth Winstead','Arlequina (Margot Robbie), Canário Negro (Jurnee Smollett), Caçadora (Mary Elizabeth Winstead), Cassandra Cain e a policial Renée Montoya (Rosie Perez) formam um grupo inusitado de heroínas. Quando um perigoso criminoso começa a causar destruição em Gotham, as cinco mulheres precisam se unir para defender a cidade.', 16,1,'Inglês','Estados Unidos',6.6,'/oFfDC7ouX63C2hj6LsF9Cm7A5Nb.jpg','/uozb2VeD87YmhoUP1RrGWfzuCrr.jpg','PEvCzJulUZI');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (3, 'Parasita', '2019-05-30', 2019, 132, 'Comédia;Thriller;Drama', 'Bong Joon-ho', 'Song Kang-ho;Lee Sun-kyun;Cho Yeo-jeong','Toda a família de Ki-taek está desempregada, vivendo num porão sujo e apertado. Uma obra do acaso faz com que o filho adolescente da família comece a dar aulas de inglês à garota de uma família rica. Fascinados com a vida luxuosa destas pessoas, pai, mãe, filho e filha bolam um plano para se infiltrarem também na família burguesa, um a um. No entanto, os segredos e mentiras necessários à ascensão social custarão caro a todos.', 16,1,'Coreano','Coreia do Sul',8.6,'/bNGW8zYA91VqTZfV3jnKHPEKKvB.jpg','/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg','ruaBfQWvHKI');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (4, 'A Hora Da Sua Morte', '2019-10-25', 2019, 90, 'Terror;Thriller', 'Justin Dec', 'Elizabeth Lail;Jordan Calloway;Talitha Bateman','Uma jovem enfermeira baixa um aplicativo que promete prever o momento e a data da morte das pessoas. Quando o aplicativo indica que ela tem três dias de vida restantes, a enfermeira luta por sua sobrevivência ao mesmo tempo em que enfrenta uma misteriosa criatura que a assombra.', 14,1,'Inglês','Estados Unidos',5.3,'/gM3CutrtmlTtLCqOShzto6ECgBX.jpg','/zETkzgle7c6wAeW11snnVUBp67S.jpg','D1S4ElaFc6A');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (5, 'Dolittle', '2020-01-17', 2020, 99, 'Comédia;Fantasia;Aventura;Família', 'Chris McKay', 'Robert Downey Jr;Antonio Banderas;Michael Sheen;','O Dr. Dolittle vive com uma variedade de animais exóticos e conversa com eles diariamente. Quando a jovem rainha Victoria fica doente, o excêntrico médico e seus amigos peludos embarcam em uma aventura épica em uma ilha mítica para encontrar a cura.', 0,1,'Inglês','Estados Unidos',5.5,'/eiMUDeDBH4s1dbtbcnmasAtgssZ.jpg','/lG802rseTZcN9mtLsQPVfApEVzM.jpg','c-hwRn94sMw');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (6, 'Bad Boys Para Sempre', '2020-01-15', 2020, 113, 'Thriller;Ação;Crime;', 'Bilall Fallah;Adil El Arbi', 'Will Smith;Martin Lawrence;Vanessa Hudgens','Armando é um assassino de sangue frio com uma natureza cruel e provocadora. Ele está comprometido com o trabalho do cartel e é enviado por sua mãe para matar Mike (Smith). Nuñez assumirá o papel de Rita, psicóloga criminal durona e engraçada que é recém-nomeada chefe da AMMO e é ex-namorada de Mike.', 16,1,'Inglês','Estados Unidos',7.2,'/Y0NQuB8cMZlmgBe90BOlMoFMSX.jpg','/upUy2QhMZEmtypPW3PdieKLAHxh.jpg','ay05Ts6wnjI');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (7, 'O Chamado da Floresta', '2020-02-19', 2020, 100, 'Aventura;Família;Drama;', 'Chris Sanders', 'Harrison Ford;Dan Stevens;Colin Woodell','Depois de anos vivendo como um cachorro de estimação na casa de uma família na Califórnia, Buck precisa entrar em contato com os seus instintos mais selvagens para conseguir sobreviver em um ambiente hostil como o Alaska. Com o tempo, seu lado feroz se desenvolve e ele se torna o grande líder de sua matilha. Baseado no livro homônimo de Jack London, lançado em 1903.', 0,1,'Inglês','Estados Unidos',6.8,'/yMZoOrAWHZ0Jtga7xQDxd024luQ.jpg','/yFRpUmsreYO5Bc0HVBTsJsHIIox.jpg','_rjeorIxeEI');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (8, 'Jojo Rabbit', '2019-10-18', 2019, 108, 'Comédia;Guerra;Drama;', 'Taika Waititi', 'Roman Griffin Davis;Thomasin McKenzie;Scarlett Johansson','Alemanha, durante a Segunda Guerra Mundial. Jojo (Roman Griffin Davis) é um jovem nazista de 10 anos, que trata Adolf Hitler (Taika Waititi) como um amigo próximo, em sua imaginação. Seu maior sonho é participar da Juventude Hitlerista, um grupo pró-nazista composto por outras pessoas que concordam com os seus ideais. Um dia, Jojo descobre que sua mãe (Scarlett Johansson) está escondendo uma judia (Thomasin McKenzie) no sótão de casa. Depois de várias tentativas frustradas para expulsá-la, o jovem rebelde começa a desenvolver empatia pela nova hóspede.', 14,1,'Inglês','Estados Unidos',8.0,'/xhJF9gStbEsvGiCIxwPu8B1NqjZ.jpg','/agoBZfL1q5G79SD0npArSlJn8BH.jpg,','-IBaMJ15Fm0');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (9, 'Jumanji: Próxima Fase', '2019-12-04', 2019, 123, 'Ação;Aventura;Comédia;Fantasia', 'Jake Kasdan', 'Dwayne Johnson;Jack Black;Kevin Hart','Tentado em revisitar o mundo de Jumanji, Spencer (Alex Wolff) decide consertar o jogo de videogame que permite que os jogadores sejam transportados ao local. Logo o quarteto formado por Smolder Bravestone (Dwayne Johnson), Moose Finbar (Kevin Hart), Shelly Oberon (Jack Black) e Ruby Roundhouse (Karen Gillan) ressurge, agora comandado por outras pessoas: os avôs de Spencer e Fridge (Danny DeVito e Danny Glover) assumem as personas de Bravestone e Finbar, enquanto o próprio Fridge (Ser Darius Blain) agora está sob a pele de Oberon.', 12,1,'Inglês','Estados Unidos',6.9,'/bBRDUTr6jgbD8I8A9DvVGrVbdfB.jpg','/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg','cadEnARIOVg');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (10, 'Frozen 2', '2019-11-20', 2019, 104, 'Animação;Família;Aventura', 'Chris Buck', 'Kristen Bell;Idina Menzel;Jonathan Groff','De volta à infância de Elsa e Anna, as duas garotas descobrem uma história do pai, quando ainda era príncipe de Arendelle. Ele conta às meninas a história de uma visita à floresta dos elementos, onde um acontecimento inesperado teria provocado a sepaação dos habitantes da cidade com os quatro elementos fundamentais: ar, fogo, terra e água. Esta revelação ajudará Elsa a compreender a origem de seus poderes.', 0,1,'Inglês','Estados Unidos',7.1,'/qXsndsv3WOoxszmdlvTWeY688eK.jpg','/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg','PPXqPxNh8lo');


INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (11, 'Sonic: O Filme', '2021-02-12', 2021, 99, 'Ação;Ficção Científica;COMÉDIA;FAMÍLIA', 'Jeff Fowler', 'Ben Schwartz;James Marsden;Jim Carrey','Sonic, o ouriço azul mais famoso do mundo, se junta com os seus amigos para derrotar o terrível Doutor Eggman, um cientista louco que planeja dominar o mundo, e o Doutor Robotnik, responsável por aprisionar animais inocentes em robôs.', 0,1,'Inglês','Estados Unidos',6.9,'/Kt9iFdTu5TbAm7tNfc876mrWU.jpg','/qonBhlm0UjuKX2sH7e73pnG0454.jpg','zQEjE_M2Esw');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (12, 'Aves de Rapina: Arlequina e sua Emancipação Fantabulosa', '2021-12-07', 2021, 109, 'Ação;Crime;Comédia', 'Cathy Yan', 'Margot Robbie;Ewan McGregor;Mary Elizabeth Winstead','Arlequina (Margot Robbie), Canário Negro (Jurnee Smollett), Caçadora (Mary Elizabeth Winstead), Cassandra Cain e a policial Renée Montoya (Rosie Perez) formam um grupo inusitado de heroínas. Quando um perigoso criminoso começa a causar destruição em Gotham, as cinco mulheres precisam se unir para defender a cidade.', 16,1,'Inglês','Estados Unidos',6.6,'/oFfDC7ouX63C2hj6LsF9Cm7A5Nb.jpg','/uozb2VeD87YmhoUP1RrGWfzuCrr.jpg','PEvCzJulUZI');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (13, 'Parasita', '2021-05-30', 2021, 132, 'Comédia;Thriller;Drama', 'Bong Joon-ho', 'Song Kang-ho;Lee Sun-kyun;Cho Yeo-jeong','Toda a família de Ki-taek está desempregada, vivendo num porão sujo e apertado. Uma obra do acaso faz com que o filho adolescente da família comece a dar aulas de inglês à garota de uma família rica. Fascinados com a vida luxuosa destas pessoas, pai, mãe, filho e filha bolam um plano para se infiltrarem também na família burguesa, um a um. No entanto, os segredos e mentiras necessários à ascensão social custarão caro a todos.', 16,1,'Coreano','Coreia do Sul',8.6,'/bNGW8zYA91VqTZfV3jnKHPEKKvB.jpg','/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg','ruaBfQWvHKI');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (14, 'A Hora Da Sua Morte', '2021-10-25', 2021, 90, 'Terror;Thriller', 'Justin Dec', 'Elizabeth Lail;Jordan Calloway;Talitha Bateman','Uma jovem enfermeira baixa um aplicativo que promete prever o momento e a data da morte das pessoas. Quando o aplicativo indica que ela tem três dias de vida restantes, a enfermeira luta por sua sobrevivência ao mesmo tempo em que enfrenta uma misteriosa criatura que a assombra.', 14,1,'Inglês','Estados Unidos',5.3,'/gM3CutrtmlTtLCqOShzto6ECgBX.jpg','/zETkzgle7c6wAeW11snnVUBp67S.jpg','D1S4ElaFc6A');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (15, 'Dolittle', '2021-01-17', 2021, 99, 'Comédia;Fantasia;Aventura;Família', 'Chris McKay', 'Robert Downey Jr;Antonio Banderas;Michael Sheen;','O Dr. Dolittle vive com uma variedade de animais exóticos e conversa com eles diariamente. Quando a jovem rainha Victoria fica doente, o excêntrico médico e seus amigos peludos embarcam em uma aventura épica em uma ilha mítica para encontrar a cura.', 0,1,'Inglês','Estados Unidos',5.5,'/eiMUDeDBH4s1dbtbcnmasAtgssZ.jpg','/lG802rseTZcN9mtLsQPVfApEVzM.jpg','c-hwRn94sMw');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (16, 'Bad Boys Para Sempre', '2021-01-15', 2021, 113, 'Thriller;Ação;Crime;', 'Bilall Fallah;Adil El Arbi', 'Will Smith;Martin Lawrence;Vanessa Hudgens','Armando é um assassino de sangue frio com uma natureza cruel e provocadora. Ele está comprometido com o trabalho do cartel e é enviado por sua mãe para matar Mike (Smith). Nuñez assumirá o papel de Rita, psicóloga criminal durona e engraçada que é recém-nomeada chefe da AMMO e é ex-namorada de Mike.', 16,1,'Inglês','Estados Unidos',7.2,'/Y0NQuB8cMZlmgBe90BOlMoFMSX.jpg','/upUy2QhMZEmtypPW3PdieKLAHxh.jpg','ay05Ts6wnjI');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (17, 'O Chamado da Floresta', '2021-02-19', 2021, 100, 'Aventura;Família;Drama;', 'Chris Sanders', 'Harrison Ford;Dan Stevens;Colin Woodell','Depois de anos vivendo como um cachorro de estimação na casa de uma família na Califórnia, Buck precisa entrar em contato com os seus instintos mais selvagens para conseguir sobreviver em um ambiente hostil como o Alaska. Com o tempo, seu lado feroz se desenvolve e ele se torna o grande líder de sua matilha. Baseado no livro homônimo de Jack London, lançado em 1903.', 0,1,'Inglês','Estados Unidos',6.8,'/yMZoOrAWHZ0Jtga7xQDxd024luQ.jpg','/yFRpUmsreYO5Bc0HVBTsJsHIIox.jpg','_rjeorIxeEI');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (18, 'Jojo Rabbit', '2021-10-18', 2021, 108, 'Comédia;Guerra;Drama;', 'Taika Waititi', 'Roman Griffin Davis;Thomasin McKenzie;Scarlett Johansson','Alemanha, durante a Segunda Guerra Mundial. Jojo (Roman Griffin Davis) é um jovem nazista de 10 anos, que trata Adolf Hitler (Taika Waititi) como um amigo próximo, em sua imaginação. Seu maior sonho é participar da Juventude Hitlerista, um grupo pró-nazista composto por outras pessoas que concordam com os seus ideais. Um dia, Jojo descobre que sua mãe (Scarlett Johansson) está escondendo uma judia (Thomasin McKenzie) no sótão de casa. Depois de várias tentativas frustradas para expulsá-la, o jovem rebelde começa a desenvolver empatia pela nova hóspede.', 14,1,'Inglês','Estados Unidos',8.0,'/xhJF9gStbEsvGiCIxwPu8B1NqjZ.jpg','/agoBZfL1q5G79SD0npArSlJn8BH.jpg,','-IBaMJ15Fm0');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (19, 'Jumanji: Próxima Fase', '2021-12-04', 2021, 123, 'Ação;Aventura;Comédia;Fantasia', 'Jake Kasdan', 'Dwayne Johnson;Jack Black;Kevin Hart','Tentado em revisitar o mundo de Jumanji, Spencer (Alex Wolff) decide consertar o jogo de videogame que permite que os jogadores sejam transportados ao local. Logo o quarteto formado por Smolder Bravestone (Dwayne Johnson), Moose Finbar (Kevin Hart), Shelly Oberon (Jack Black) e Ruby Roundhouse (Karen Gillan) ressurge, agora comandado por outras pessoas: os avôs de Spencer e Fridge (Danny DeVito e Danny Glover) assumem as personas de Bravestone e Finbar, enquanto o próprio Fridge (Ser Darius Blain) agora está sob a pele de Oberon.', 12,1,'Inglês','Estados Unidos',6.9,'/bBRDUTr6jgbD8I8A9DvVGrVbdfB.jpg','/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg','cadEnARIOVg');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (20, 'Frozen 2', '2021-11-20', 2021, 104, 'Animação;Família;Aventura', 'Chris Buck', 'Kristen Bell;Idina Menzel;Jonathan Groff','De volta à infância de Elsa e Anna, as duas garotas descobrem uma história do pai, quando ainda era príncipe de Arendelle. Ele conta às meninas a história de uma visita à floresta dos elementos, onde um acontecimento inesperado teria provocado a sepaação dos habitantes da cidade com os quatro elementos fundamentais: ar, fogo, terra e água. Esta revelação ajudará Elsa a compreender a origem de seus poderes.', 0,1,'Inglês','Estados Unidos',7.1,'/qXsndsv3WOoxszmdlvTWeY688eK.jpg','/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg','PPXqPxNh8lo');

INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (21, 'Bad Boys Para Sempre', '2020-01-15', 2020, 113, 'Thriller;Ação;Crime;', 'Bilall Fallah;Adil El Arbi', 'Will Smith;Martin Lawrence;Vanessa Hudgens','Armando é um assassino de sangue frio com uma natureza cruel e provocadora. Ele está comprometido com o trabalho do cartel e é enviado por sua mãe para matar Mike (Smith). Nuñez assumirá o papel de Rita, psicóloga criminal durona e engraçada que é recém-nomeada chefe da AMMO e é ex-namorada de Mike.', 16,0,'Inglês','Estados Unidos',7.2,'/Y0NQuB8cMZlmgBe90BOlMoFMSX.jpg','/upUy2QhMZEmtypPW3PdieKLAHxh.jpg','ay05Ts6wnjI');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (22, 'O Chamado da Floresta', '2020-02-19', 2020, 100, 'Aventura;Família;Drama;', 'Chris Sanders', 'Harrison Ford;Dan Stevens;Colin Woodell','Depois de anos vivendo como um cachorro de estimação na casa de uma família na Califórnia, Buck precisa entrar em contato com os seus instintos mais selvagens para conseguir sobreviver em um ambiente hostil como o Alaska. Com o tempo, seu lado feroz se desenvolve e ele se torna o grande líder de sua matilha. Baseado no livro homônimo de Jack London, lançado em 1903.', 0,0,'Inglês','Estados Unidos',6.8,'/yMZoOrAWHZ0Jtga7xQDxd024luQ.jpg','/yFRpUmsreYO5Bc0HVBTsJsHIIox.jpg','_rjeorIxeEI');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (23, 'Jojo Rabbit', '2019-10-18', 2019, 108, 'Comédia;Guerra;Drama;', 'Taika Waititi', 'Roman Griffin Davis;Thomasin McKenzie;Scarlett Johansson','Alemanha, durante a Segunda Guerra Mundial. Jojo (Roman Griffin Davis) é um jovem nazista de 10 anos, que trata Adolf Hitler (Taika Waititi) como um amigo próximo, em sua imaginação. Seu maior sonho é participar da Juventude Hitlerista, um grupo pró-nazista composto por outras pessoas que concordam com os seus ideais. Um dia, Jojo descobre que sua mãe (Scarlett Johansson) está escondendo uma judia (Thomasin McKenzie) no sótão de casa. Depois de várias tentativas frustradas para expulsá-la, o jovem rebelde começa a desenvolver empatia pela nova hóspede.', 14,0,'Inglês','Estados Unidos',8.0,'/xhJF9gStbEsvGiCIxwPu8B1NqjZ.jpg','/agoBZfL1q5G79SD0npArSlJn8BH.jpg,','-IBaMJ15Fm0');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (24, 'Jumanji: Próxima Fase', '019-12-04', 2019, 123, 'Ação;Aventura;Comédia;Fantasia', 'Jake Kasdan', 'Dwayne Johnson;Jack Black;Kevin Hart','Tentado em revisitar o mundo de Jumanji, Spencer (Alex Wolff) decide consertar o jogo de videogame que permite que os jogadores sejam transportados ao local. Logo o quarteto formado por Smolder Bravestone (Dwayne Johnson), Moose Finbar (Kevin Hart), Shelly Oberon (Jack Black) e Ruby Roundhouse (Karen Gillan) ressurge, agora comandado por outras pessoas: os avôs de Spencer e Fridge (Danny DeVito e Danny Glover) assumem as personas de Bravestone e Finbar, enquanto o próprio Fridge (Ser Darius Blain) agora está sob a pele de Oberon.', 12,0,'Inglês','Estados Unidos',6.9,'/bBRDUTr6jgbD8I8A9DvVGrVbdfB.jpg','/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg','cadEnARIOVg');
INSERT INTO filme (id, titulo, data_lancamento, ano, duracao, genero, diretor, atores, sinopse, classificacao, em_cartaz, idioma, pais, imdb, poster, banner, trailer_url) VALUES (25, 'Frozen 2', '2019-11-20', 2019, 104, 'Animação;Família;Aventura', 'Chris Buck', 'Kristen Bell;Idina Menzel;Jonathan Groff','De volta à infância de Elsa e Anna, as duas garotas descobrem uma história do pai, quando ainda era príncipe de Arendelle. Ele conta às meninas a história de uma visita à floresta dos elementos, onde um acontecimento inesperado teria provocado a sepaação dos habitantes da cidade com os quatro elementos fundamentais: ar, fogo, terra e água. Esta revelação ajudará Elsa a compreender a origem de seus poderes.', 0,0,'Inglês','Estados Unidos',7.1,'/qXsndsv3WOoxszmdlvTWeY688eK.jpg','/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg','PPXqPxNh8lo');